"""Cloud dashboard updater — writes cloud agent status to Updates/cloud_status.md.

PLATINUM TIER MODIFICATION:
    Cloud agent writes to Updates/cloud_status.md (NOT Dashboard.md directly).
    Local agent merges Updates/ into Dashboard.md to prevent Git conflicts.
"""

import json
from datetime import datetime, timezone
from pathlib import Path


def update_dashboard(
    vault_path: str | Path,
    watcher_status: dict | None = None,
    service_health: dict | None = None,
    odoo_summary: dict | None = None,
) -> Path:
    """Write cloud agent status to Updates/cloud_status.md.

    Args:
        vault_path: Path to AI_Employee_Vault
        watcher_status: Dict of watcher names → status strings
        service_health: Dict of service names → health status (unused on cloud)
        odoo_summary: Odoo financial snapshot (unused on cloud)

    Returns:
        Path to the written status file (Updates/cloud_status.md)
    """
    vault = Path(vault_path).resolve()
    updates_dir = vault / "Updates"
    updates_dir.mkdir(exist_ok=True)

    status_file = updates_dir / "cloud_status.md"

    # INVARIANT: Cloud agent NEVER writes to Dashboard.md directly
    if "Dashboard.md" in str(status_file):
        raise RuntimeError(
            "SECURITY: Cloud agent attempted to write Dashboard.md directly. "
            "Cloud must only write to Updates/cloud_status.md to prevent merge conflicts."
        )
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    now_iso = datetime.now(timezone.utc).isoformat()

    # Count files in various directories (recursive for domain subdirectories)
    needs_action = vault / "Needs_Action"
    in_progress_cloud = vault / "In_Progress" / "cloud"
    pending_approval = vault / "Pending_Approval"

    needs_action_count = sum(1 for f in needs_action.glob("**/*.md") if f.is_file()) if needs_action.exists() else 0
    in_progress_count = sum(1 for f in in_progress_cloud.glob("**/*.md") if f.is_file()) if in_progress_cloud.exists() else 0
    pending_approval_count = sum(1 for f in pending_approval.glob("**/*.md") if f.is_file()) if pending_approval.exists() else 0

    # Get watcher status
    gmail_status = "offline"
    if watcher_status and "GmailWatcher" in watcher_status:
        gmail_status = "online" if "Online" in watcher_status["GmailWatcher"] else "offline"

    # Build cloud status content
    content = f"""---
agent: cloud
last_updated: {now_iso}
gmail_status: {gmail_status}
needs_action_count: {needs_action_count}
in_progress_count: {in_progress_count}
pending_approval_count: {pending_approval_count}
---

# Cloud Agent Status

**Last Updated:** {now_str}

## Watchers
- Gmail: {gmail_status}

## File Counts
- Needs_Action: {needs_action_count}
- In_Progress/cloud: {in_progress_count}
- Pending_Approval: {pending_approval_count}

---
*This file is auto-generated by the Cloud Agent. The Local Agent merges it into Dashboard.md.*
"""

    # Atomic write (temp file + rename)
    temp_file = status_file.with_suffix(".tmp")
    temp_file.write_text(content, encoding="utf-8")
    temp_file.rename(status_file)

    return status_file
